name=input("enter your name")
print(name)
print("isalnum: ", name.isalnum())
print("isalalpha: ", name.isalpha())
print("isdigit:", name.isdigit())
print("islower:", name.islower())
print("isupper:", name.isupper())
print("capitalize:", name.capitalize())
print("find: ", name.find("h", 0, len(name)))
str=input("Enter a string or char to find number of occurances")
print("{} occured {} times".format(str,name.count(str,0,len(name))))
print(name.upper())
print(name.lower())
print(name.lstrip())
print(name.rstrip())
print(name.replace('r','s'))
print(name.split())
print('-'.join(['26','02','2022']))

a=int(input("Enter a"))
b=int(input("Enter b"))
c=a+b
print("the sum of {} and {} is {}".format(a,b,c))
