s=input('enter any string')
print('String is {}'.format(s))
print('s[1:5]',s[1:5])
print('s[:]',s[:])
print('s[4:]',s[4:])
print('s[:3]',s[:3])
print('s[0:5:2]',s[0:5:2])
print('s[:-1]',s[:-1])
print('s[::-1]',s[::-1])
print('s[::-2]',s[::-2])
print('s[-4:-1]',s[-4:-1])
print('s[-4:-2]',s[-4:-2])
